### PR TITLE
YOOOOOO MORE SUPPORTTTT

### PR DESCRIPTION
**Pull request by Chickensoup20**
B)

### CODE REVIEW

**Comment by AstroSquared** [comment]
a

**Review by AstroSquared — APPROVED** [review]
i didnt even read

**Comment by Wonkers0** [comment]
Who do you think you are astro only I get to approve changes 😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡

**Comment by AstroSquared** [comment]
o                             k

**Comment by Chickensoup20** [comment]
goofy review

**Comment by Chickensoup20** [comment]
11/10

**Comment by CheaterTim** [comment]
|| ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ||

**Comment by AstroSquared** [comment]
hey cheatertim...

**Comment by CheaterTim** [comment]
1 s

**Comment by Chickensoup20** [comment]
cheating tim joined the chat

**Comment by Chickensoup20** [comment]
goofy ahh

**Comment by AstroSquared** [comment]
> 1 s

deez.nuts user

**Comment by CheaterTim** [comment]
j

**Review by GeorgeRNG — COMMENTED** [review]
honestly quite incredible

**Comment by CheaterTim** [comment]
wtf go back to logging the requesters ip

**Comment by AstroSquared** [comment]
do we really need this many comments that are off topic

**Comment by Chickensoup20** [comment]
**### 

@ #1. > `[truth](url)`

**

**Comment by CheaterTim** [comment]
yes

**Comment by CheaterTim** [comment]
> **###
> 
> @ #1. > `[truth](url)`
> 
> **

ok

**Comment by GeorgeRNG** [comment]
127.0.0.1

**Comment by AstroSquared** [comment]
> wtf go back to logging the requesters ip

> 127.0.0.1

https://github.com/UserUNP/sparkscript/commit/1f3c171bb34f2177ae72ed38396f3b73e979a79a#r79740532

**Comment by Wonkers0** [comment]
this is the part where I shut you all up

**Review by GeorgeRNG — COMMENTED** [review]
No

**Comment by Wonkers0** [comment]
the webhook literally got ratelimited

**Comment by CheaterTim** [comment]
no

**Comment by SquaredStudios-MC** [comment]
> the webhook literally got ratelimited

why dont you

cope

**Comment by CheaterTim** [comment]
:+1:

**Comment by CheaterTim** [comment]
guys we have to make wonker cope hardest

**Comment by SquaredStudios-MC** [comment]
how

**Comment by CheaterTim** [comment]
uhhhh

**Comment by CheaterTim** [comment]
idk

**Comment by SquaredStudios-MC** [comment]
@Wonkers0 stop deleting comments

**Comment by CheaterTim** [comment]
censorship

**Comment by SquaredStudios-MC** [comment]
@Wonkers0 who asked

**Comment by AstroSquared** [comment]
bru whats wrong

**Comment by Chickensoup20** [comment]
xD

**Comment by AstroSquared** [comment]
> 

tru

**Comment by AstroSquared** [comment]
@Wonkers0 right now

censored

**Comment by CheaterTim** [comment]
added to favourietidtioes on discorder

**Comment by AstroSquared** [comment]
dead chat xd

**Comment by AstroSquared** [comment]
@Wonkers0 merge the pr or smthing xddddddddddddddddd

**Comment by CheaterTim** [comment]
:nerd_face:

**Comment by Chickensoup20** [comment]
wait did it actually work????

**Comment by Chickensoup20** [comment]
like my changes werent deleted

**Comment by AstroSquared** [comment]
;-;
you said you wouldn’t merge this

**Comment by Chickensoup20** [comment]
cry

**Comment by Wonkers0** [comment]
> ;-; you said you wouldn’t merge this

@SquaredStudios-MC My version of the project (stored locally) is always ahead of the main branch, as I am actively working on the project. I try to commit after adding big features though, so if somebody contributes in that gray period between a commit and a big update that is not yet finished, I cannot commit it as it would create massive backwards compatibility issues

**Comment by AstroSquared** [comment]
normally you just merge the pr but ok

**Comment by AstroSquared** [comment]
image

**Comment by Wonkers0** [comment]
> normally you just merge the pr but ok

I just told you why I can't

**Comment by GeorgeRNG** [comment]
> > ;-; you said you wouldn’t merge this
> 
> @SquaredStudios-MC My version of the project (stored locally) is always ahead of the main branch, as I am actively working on the project. I try to commit after adding big features though, so if somebody contributes in that gray period between a commit and a big update that is not yet finished, I cannot commit it as it would create massive backwards compatibility issues

You could perhaps have a production branch, and development branch which allows people to work in stuff in development and makes it so you project is lively tracked on GitHub, ever be the case you have to redownload the project, and loose as little progress as possible

**Pull request merged**
